server {
    listen 80;
    server_name localhost;

    # Arquivos estáticos
    location /static/ {
        alias /usr/share/nginx/html/static/;
    }

    # Página principal
    location = / {
        root /usr/share/nginx/html;
        try_files /static/index.html =404;
    }

    # API -> proxy para o backend
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_buffering off;
        client_max_body_size 50M;
    }
}
